# Enabled?
Enabled: true

# --------------
# --- Cryper ---
# --------------

# Is the creeper module enabled?
CreeperModule_enabled: true

# Should the damage take place on the players or not.
LeaveDamage: true

# Should I turn off the explosions altogether?
DisableExplosions: true
# Those blocks that should not break when the creeper explodes.
Creeper_blocks:
  - "diamond_block"

#permission -> toolscreeper.admin

# -----------------
# --- JumpTools ---
# -----------------

# Is the jump module enabled?
JumpModule_enabled: true

# These values are responsible for how many percent the player's speed will be increased, or vice versa reduced. (In %)
JumpSpeed: 5
NormalSpeed: 12

# Messages.
JumpAccelerate: '&aYou have been accelerated!'
JumpDecelerate: '&cYou have been slowed down!'

#permission -> toolsjump.admin

# -----------------
# -- OP BLOCATOR --
# -----------------

# Is the op module enabled?
OpModule_enabled: true

OpMessage: "&4 You cant use this!"

# -----------------
# --  NEO-FETCH  --
# -----------------

# Is the fetch module enabled?
FetchModule_enabled: true

# Only the console can perform actions or not?
ForConsole: true

#permission -> toolsfetch

# -----------------
# ---  CLEANER  ---
# -----------------

# The fields below are responsible for the chat and console cleanup commands, respectively.

CleanChatModule_enabled: true

CleanConsoleModule_enabled: true

#permission -> toolschat.free
#permission -> toolsconsole.free

# -----------------
# --- OPTIMIZE  ---
# -----------------

# The fields below are responsible for using the optimization module.
OptimizationModule_enabled: true

# After how long to remove the lying objects.
abandonedObjectTimer: 5

maxChunksPerTick: 100

autostart: true

#permission -> toolsoptimize.admin